# Generated by Django 5.0.8 on 2026-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionHourlyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.CharField(db_index=True, max_length=64)),
                ('hour_bucket', models.DateTimeField(db_index=True)),
                ('avg_speed_kph', models.FloatField()),
                ('avg_congestion_level', models.FloatField()),
            ],
            options={
                'db_table': 'congestion_hourly_agg',
                'ordering': ['hour_bucket'],
                'unique_together': {('segment_id', 'hour_bucket')},
            },
        ),
    ]
