# Generated by Django 5.0.8 on 2026-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(default='ingest', max_length=32)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kph', models.FloatField()),
                ('congestion_level', models.FloatField()),
                ('recorded_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'traffic_readings',
                'indexes': [models.Index(fields=['segment_id', '-recorded_at'], name='traffic_rea_segment_25bac1_idx')],
            },
        ),
    ]
